<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# 1D Numpy in Python

Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Import and use the `numpy` library
*   Perform operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="pre">Preparation</a></li>
        <li>
            <a href="numpy">What is Numpy?</a>
            <ul>
                <li><a href="type">Type</a></li>
                <li><a href="val">Assign Value</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="list">Assign Value with List</a></li>
                <li><a href="other">Other Attributes</a></li>
            </ul>
        </li>
        <li>
            <a href="op">Numpy Array Operations</a>
            <ul>
                <li><a href="add">Array Addition</a></li>
                <li><a href="multi">Array Multiplication</a></li>
                <li><a href="prod">Product of Two Numpy Arrays</a></li>
                <li><a href="dot">Dot Product</a></li>
                <li><a href="cons">Adding Constant to a Numpy Array</a></li>
            </ul>
        </li>
        <li><a href="math">Mathematical Functions</a></li>
        <li><a href="lin">Linspace</a></li>
    </ul>

</div>

<hr>


<h2 id="pre">Preparation</h2>


In [ ]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [ ]:
# Plotting functions

def Plotvec1(u, z, v):
    
    ax = plt.axes()
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)
    plt.text(*(u + 0.1), 'u')
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)
    plt.text(*(v + 0.1), 'v')
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

Create a Python List as follows:


In [ ]:
# Create a python list

a = ["0", 1, "two", "3", 4]

We can access the data via an index:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneList.png" width="660" />


We can access each element using a square bracket as follows:


In [2]:
# Print each element

a = ["0", 1, "two", "3", 4]

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


<hr>


<h2 id="numpy">What is Numpy?</h2>


A numpy array is similar to a list. It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing `numpy`:


In [ ]:
# import numpy library

import numpy as np 

We then cast the list as follows:


In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

Each element is of the same type, in this case integers:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500" />


As with lists, we can access each element via a square bracket:


In [4]:
# Print each element

import numpy as np

a = np.array([0, 1, 2, 3, 4])

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


<h3 id="type">Type</h3>


If we check the type of the array we get <b>numpy.ndarray</b>:


In [5]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the data type of the array’s elements. In this case, it's a 64-bit integer:


In [6]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

We can create a numpy array with real numbers:


In [11]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print(b)

[  3.1   11.02   6.2  213.2    5.2 ]


When we check the type of the array we get <b>numpy.ndarray</b>:


In [12]:
# Check the type of array

type(b)

numpy.ndarray

If we examine the attribute <code>dtype</code> we see float 64, as the elements are not integers:


In [13]:
# Check the value type

b.dtype

dtype('float64')

<h3 id="val">Assign value</h3>


We can change the value of the array. Consider the array <code>c</code>:


In [14]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:


In [15]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

We can change the 5th element of the array to 0 as follows:


In [16]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

<h3 id="slice">Slicing</h3>


Like lists, we can slice the numpy array. We can select the elements from 1 to 3 and assign it to a new numpy array <code>d</code> as follows:


In [17]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values as follows:


In [19]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

<h3 id="list">Assign Value with List</h3>


Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:


In [26]:
# Create the index list

select = [0, 2, 3]

We can use the list as an argument in the brackets. The output is the elements corresponding to the particular indexes:


In [25]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

We can assign the specified elements to a new value. For example, we can assign the values to 100 000 as follows:


In [27]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

<h3 id="other">Other Attributes</h3>


Let's review some basic array attributes using the array <code>a</code>:


In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

The attribute <code>size</code> is the number of elements in the array:


In [28]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute <code>ndim</code> represents the number of array dimensions, or the rank of the array. In this case, one:


In [29]:
# Get the number of dimensions of numpy array

a.ndim

1

The attribute <code>shape</code> is a tuple of integers indicating the size of the array in each dimension:


In [30]:
# Get the shape/size of numpy array

a.shape

(5,)

In [35]:
# Create a numpy array

import numpy as np

a = np.array([1, -1, 1, -1])
print(a)

[ 1 -1  1 -1]


In [40]:
# Get the mean of numpy array

a.mean()

0.0

In [41]:
# Get the standard deviation of numpy array

a.std()

1.0

In [38]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [39]:
# Get the biggest value in the numpy array

b.max()

5

In [42]:
# Get the smallest value in the numpy array

b.min()

-1

<hr>


<h2 id="op">Numpy Array Operations</h2>


<h3 id="add">Array Addition</h3>


Consider the numpy array <code>u</code>:


In [ ]:
u = np.array([1, 0])
u

Consider the numpy array <code>v</code>:


In [ ]:
v = np.array([0, 1])
v

We can add the two arrays and assign it to z:


In [44]:
# Numpy Array Addition

import numpy as np

u = np.array([1, 0])
v = np.array([0, 1])

z = u + v
print(z)

[1 1]


The operation is equivalent to vector addition:


In [48]:
# Plot numpy arrays

import numpy as np

u = np.array([1, 0])
v = np.array([0, 1])
z = u + v

Plotvec1(u, z, v)

NameError: name 'Plotvec1' is not defined

<h3 id="multi">Array Multiplication</h3>


Consider the vector numpy array <code>y</code>:


In [ ]:
# Create a numpy array

y = np.array([1, 2])
y

We can multiply every element in the array by 2:


In [ ]:
# Numpy Array Multiplication

z = 2 * y
z

This is equivalent to multiplying a vector by a scaler:


<h3 id="prod">Product of Two Numpy Arrays</h3>


Consider the following array <code>u</code>:


In [ ]:
# Create a numpy array

u = np.array([1, 2])
u

Consider the following array <code>v</code>:


In [ ]:
# Create a numpy array

v = np.array([3, 2])
v

The product of the two numpy arrays <code>u</code> and <code>v</code> is given by:


In [51]:
# Calculate the production of two numpy arrays

import numpy as np

u = np.array([1, 2])
v = np.array([3, 2])

z = u * v
print(z)

[3 4]


<h3 id="dot">Dot Product</h3>


The dot product of the two numpy arrays <code>u</code> and <code>v</code> is given by:


In [52]:
# Calculate the dot product

np.dot(u, v)

7

<h3 id="cons">Adding Constant to a Numpy Array</h3>


Consider the following array:


In [55]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

Adding the constant 1 to each element in the array:


In [54]:
# Add the constant to array

import numpy as np
u = np.array([1, 2, 3, -1]) 
x = u + 1

print(x)

[2 3 4 0]


The process is summarised in the following animation:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneAdd.gif" width="500" />


<hr>


<h2 id="math">Mathematical Functions</h2>


We can access the value of <code>pi</code> in numpy as follows :


In [56]:
# The value of pi

np.pi

3.141592653589793

We can create the following numpy array in Radians:


In [62]:
# Create the numpy array in radians

import numpy as np
x = np.array([0, np.pi/2 , np.pi])
print(x)

[0.         1.57079633 3.14159265]


We can apply the function <code>sin</code> to the array <code>x</code> and assign the values to the array <code>y</code>; this applies the sine function to each element in the array:


In [63]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

<hr>


<h2 id="lin">Linspace</h2>


A useful function for plotting mathematical functions is <code>linspace</code>.   Linspace returns evenly spaced numbers over a specified interval. We specify the starting point of the sequence and the ending point of the sequence. The parameter "num" indicates the Number of samples to generate, in this case 5:


In [64]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

If we change the parameter <code>num</code> to 9, we get 9 evenly spaced numbers over the interval from -2 to 2:


In [65]:
# Make a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

We can use the function <code>linspace</code> to generate 100 evenly spaced samples from the interval 0 to 2π:


In [69]:
# Make a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

We can apply the sine function to each element in the array <code>x</code> and assign it to the array <code>y</code>:


In [71]:
# Calculate the sine of x list

y = np.sin(x)
print(y)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [75]:
# Plot the result

plt.plot(x,y)

NameError: name 'plt' is not defined

<hr>


<h2 id="quiz">Quiz on 1D Numpy Array</h2>


Implement the following vector subtraction in numpy: u-v


In [77]:
# Write your code below and press Shift+Enter to execute

import numpy as np

u = np.array([1, 0])
v = np.array([0, 1])

z = u - v 
print(z)

[ 1 -1]


<details><summary>Click here for the solution</summary>

```python
u - v
```

</details>


<hr>


Multiply the numpy array z with -2:


In [79]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])
x = -2 * z
print(x)

[-4 -8]


<details><summary>Click here for the solution</summary>

```python
-2 * z
```

</details>


<hr>


Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [87]:
# Write your code below and press Shift+Enter to execute

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
c  = (a * b)
print(c)

[1 0 3 0 5]


<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b
```

</details>


<hr>


Convert the list <code>\[-1, 1]</code> and <code>\[1, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then, plot the arrays as vectors using the fuction <code>Plotvec2</code> and find their dot product:


In [94]:
# Write your code below and press Shift+Enter to execute

import numpy as np

a = np.array([-1, 1])
b = np.array([1, 1])
print("The dot product is", np.dot(a,b))

The dot product is 0


<details><summary>Click here for the solution</summary>

```python
a = np.array([-1, 1])
b = np.array([1, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a,b))

```

</details>


<hr>


Convert the list <code>\[1, 0]</code> and <code>\[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then, plot the arrays as vectors using the function <code>Plotvec2</code> and find their dot product:


In [96]:
# Write your code below and press Shift+Enter to execute

import numpy as np

a = np.array([1, 0])
b = np.array([0, 1])
print("The dot product is", np.dot(a,b))

The dot product is 0


<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 0])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))

```

</details>


<hr>


Convert the list <code>\[1, 1]</code> and <code>\[0, 1]</code> to numpy arrays <code>a</code> and <code>b</code>. Then plot the arrays as vectors using the fuction <code>Plotvec2</code> and find their dot product:


In [97]:
# Write your code below and press Shift+Enter to execute

import numpy as np

a = np.array([1, 0])
b = np.array([1, 1])
print("The dot product is", np.dot(a,b))

The dot product is 1


<details><summary>Click here for the solution</summary>

```python
a = np.array([1, 1])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))

```

</details>


<hr>


Why are the results of the dot product for <code>\[-1, 1]</code> and <code>\[1, 1]</code> and the dot product for <code>\[1, 0]</code> and <code>\[0, 1]</code> zero, but not zero for the dot product for <code>\[1, 1]</code> and <code>\[0, 1]</code>? <p><i>Hint: Study the corresponding figures, pay attention to the direction the arrows are pointing to.</i></p>


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
The vectors used for question 4 and 5 are perpendicular. As a result, the dot product is zero. 

```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. So, please read and follow <a href="https://cognitiveclass.ai/blog/data-scientists-stand-out-by-sharing-your-notebooks/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01" target="_blank">this article</a> to learn how to share your work.
<hr>


## Author

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01" target="_blank">Joseph Santarcangelo</a>

## Other contributors

<a href="www.linkedin.com/in/jiahui-mavis-zhou-a4537814a">Mavis Zhou</a>

## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2020-08-26  | 2.0  | Lavanya | Moved lab to course repo in GitLab |
|   |   |   |   |
|   |   |   |   |

<hr/>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
